x-qwc-service-variables: &qwc-service-variables
  JWT_SECRET_KEY: $JWT_SECRET_KEY
  JWT_COOKIE_CSRF_PROTECT: 'True'
  TENANT_HEADER: tenant
  DEBUG: 'True'

services:
  mapproxy-bgeo:
    build: ../mapproxy-service
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/mapproxy'
    ports:
      # - "8088:80"
      - "127.0.0.1:9090:80"
    volumes:
      - ./pg_service.conf:/srv/pg_service.conf:ro
      - ./volumes/mapproxy/config/example:/srv/qwc_service/mapproxy/config # Where the config files are stored
      - ./volumes/mapproxy/tiles/example:/srv/qwc_service/mapproxy/tiles # Where the tiles are stored, recommended to use a fast SSD with plenty of storage
      - ./volumes/mapproxy/logs:/logs

  qwc-qgis-server:
    image: sourcepole/qwc-qgis-server:3.34-plugins
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - ./qgis-projects:/data:rw # Where the QGIS projects are stored
      - ./pg_service.conf:/etc/postgresql-common/pg_service.conf # Postgres connection configuration
    environment:
      - FCGI_IO_TIMEOUT=480
      - FCGI_MIN_PROCESSES=12
      - FCGI_MAX_PROCESSES=400
      - FCGI_PROCESS_LIFE_TIME=14400
      - FCGI_IDLE_TIMEOUT=1200
      - FCGI_MAX_REQUESTLEN=104857600
      - FCGI_CONNECT_TIMEOUT=240
      - FCGID_EXTRA_ENV=FCGI_IO_TIMEOUT,FCGI_MIN_PROCESSES,FCGI_MAX_PROCESSES,FCGI_PROCESS_LIFE_TIME,FCGI_IDLE_TIMEOUT,FCGI_MAX_REQUESTLEN,FCGI_CONNECT_TIMEOUT

  qwc-api-gateway:
    image: nginx:1.19
    ports:
      - "127.0.0.1:8098:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Nginx configuration
    depends_on:
      - mapproxy-bgeo
