db_url: postgresql:///?service=giswater_service_example # PostgreSQL connection configuration for the read-only replica database (pg_service.conf)
db_url_remote: postgresql:///?service=giswater_service_example # PostgreSQL connection configuration for the master remote database (pg_service.conf)
tiling_db_schema: tiled # Schema containing the tiling data
tileclusters_table: tiled.ws_t_tileclusters # Materialized view for storing tile clusters
data_db_schema: ws # Schema containing the data
crs: EPSG:31982 # Coordinate reference system (CRS) used in your project

# Tables used to check for updates
update_tables: [
  link,
  arc,
  connec,
  node
]

# Materialized views to be used as sources
materialized_views: [
  tiled.ws_t_link,
  tiled.ws_t_arc,
  tiled.ws_t_connec,
  tiled.ws_t_node
]

# List of selector commands to select what combinations are tiled:
#  M: Municipality
#  E: Exploitation
#  S: Sector
#  T: sTate
selectors: [
  E: true,
  T: [0, 1],
]

# Sources to be used in the mapproxy configuration (QGIS project and layers)
sources:
  inventory_source:
    url: http://qwc-qgis-server/ows/?MAP=/data/ws.qgs&USER=tileuser
    layers: ws_t_link,ws_t_arc,ws_t_connec,ws_t_node

grid:
  srs: EPSG:31982
  origin: nw
  bbox: [601843, 8128564, 747781, 8208982]

# mapproxy-util scales -l 10 --as-res-config 20000 --dpi 96
res: [
# res            level     scale @96.0 DPI
  5.2916666667, #  0       20000.00000000
  2.6458333333, #  1       10000.00000000
  1.3229166667, #  2        5000.00000000
  0.6614583333, #  3        2500.00000000
  0.3307291667, #  4        1250.00000000
  0.1653645833, #  5         625.00000000
  0.0826822917, #  6         312.50000000
  0.0413411458, #  7         156.25000000
  0.0206705729, #  8          78.12500000
  0.0103352865, #  9          39.06250000
]


